<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

       <title>{{ $page->title }} </title>
        <meta name="description" content="{!! $page->meta_description !!}">
        <script src="https://www.google.com/recaptcha/api.js?render=6Ld8BN4pAAAAAJzVLVMCYcUtUfuQN89c3iXxhotO"></script>
        <!-- Bootstrap CSS -->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

        <!-- Popper JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

        <!-- Bootstrap JS -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/css/styles.css" rel="stylesheet" />

            <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
        {
            "@context" : "http://schema.org",
            "@type" : "LocalBusiness",
            "name" : "Thats a Wrao",
            "image" : "{{ url('images/albion-og.jpg') }}",
            "telephone" : "",
            "email" : "",
            "address" : {
                "@type" : "PostalAddress",
                "streetAddress" : "",
                "addressRegion" : "",
                "addressCountry" : "United Kingdom",
                "postalCode" : ""
            },
            "url" : "{{ URL::current() }}"
        }
        </script>

        <script type=”application/ld+json”>
        {
            "@context" : "http://schema.org",
            "@type" : "Organization",
            "name" : "Albion Strategic Consulting",
            "url" : "{{ URL::current() }}",

        }
    </script>
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <td style="padding: 40px; text-align: left; color: #FFF;">
                    <a href=""><img src="{{ url('\assets\img\DAWlogo.png') }}"style="width: 120px;" alt="Thats a Rap"></a>
                </td>
                <!-- <a class="navbar-brand" href="#page-top">Start Bootstrap</a> -->
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#services">Services</a></li>
                        <li class="nav-item"><a class="nav-link" href="#gallery">Gallery</a></li>
                        <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Masthead-->
       @if(in_array($bannerextension, Page::video_mime_types()))
        <!-- style="background-image: url(' echo Storage::url($banner); ?>');" -->
        <header class="masthead"  >
        <video class="video-background" autoplay muted loop>
                <source src="{{ url('\assets\img\test.mp4') }}" type="video/mp4">
                Your browser does not support the video tag.
            </video>
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">{{ $page->title }}</h1>
                        <hr class="divider" />
                    </div>
                </div>
            </div>
        </header>
   
        <style>
 
            .video-background {
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                object-fit: cover;
                z-index: -1;
            }

        </style>
    @elseif(in_array($bannerextension, Page::image_mime_types()))
        <!-- Masthead-->
        <header class="masthead" style="background-image: url('<?php echo Storage::url($banner); ?>');">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">{{ $page->title }}</h1>
                        <hr class="divider" />
                    </div>
                </div>
            </div>
        </header>
        @endif
   
 
